# site settings
title: Akos Paha
email: paha.akos@gmail.com
description: Custom Roms, Custom Kernels Tester, Gboard Themes Maker and hobby photographer
landing-title: Hello, My Name is Akos Paha
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Akos Paha
street_address: 
city: Budapest
state: Municipality of Budapest
zip_code: 1123
country: Hungary
logo: 'assets/images/logo.jpg' # has to be a jpg image
about-text: 19 years old custom roms, custom kernels tester and Google Keyboard theme creator. I'm a 13th grade high school student. Previous school year I graduated. I take pictures of my spare time, translate apps and make keyboard themes.

# homepage config
tiles-count: 4
post-tiles: true
projects-tiles: true
home-about: false

# social settings
disqus: 'akospaha-tk'
facebook_url: https://www.facebook.com/Paha.Akos
github_url: https://github.com/AkosPaha
instagram_url: https://instagram.com/Akos_paha
paypal_url: https://www.paypal.me/akospaha
techindeep_url: https://www.techindeep.com/hu/author/akospaha
telegram_channel_url: https://t.me/paha_akos_channel
xda_url: https://forum.xda-developers.com/member.php?s=ce4ded8b84429ed989b6a7bdbb0c4ec4&u=7675009


# skills widget
skills:
  Designing: "50"
  HTML: "80"
  C#: "35"
  C++: "15"
  Office: "95"
  Testing: "100"
  Helping: "100"

# build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: :path

permalink: pretty
permalink: /:title/

jekyll_admin:
  hidden_links:
    - datafiles
